name: apllication_book_now
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  persistent_bottom_nav_bar: ^6.2.1
  table_calendar: ^3.1.2
  get: ^4.6.6
  http: ^1.2.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  fl_chart: ^0.69.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  device_info_plus: ^10.1.2
  mailer: ^6.2.0
  pinput: ^5.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  awesome_notifications: ^0.9.3+1
  overlay_support: ^2.1.0
  flutter_animate: ^4.5.0
  ticket_widget: ^1.0.2
  dotted_line: ^3.2.2
  flutter_local_notifications: ^17.2.3
  firebase_database: ^11.1.4
  flutter_date_pickers: ^0.4.3
  timezone: ^0.9.4
  responsive_grid: ^2.4.4
  badges: ^3.1.2
  restart_app: ^1.2.1
  connectivity_plus: ^6.1.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/image/
    - assets/image/logo/
    - assets/image/splash_screen/
    - assets/image/tes/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
