// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXuFfVFHx90cB7tSq28evDz2Gqh8AZwbU',
    appId: '1:318417662678:web:753912f6d48df606978f77',
    messagingSenderId: '318417662678',
    projectId: 'antriqu-apps',
    authDomain: 'antriqu-apps.firebaseapp.com',
    storageBucket: 'antriqu-apps.appspot.com',
    databaseURL:
        "https://antriqu-apps-default-rtdb.asia-southeast1.firebasedatabase.app",
    measurementId: 'G-7FMJP3F4JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc77n3K138XUjHVpzHOE2y3Wyg9dXx4po',
    appId: '1:318417662678:android:9e0d1cace8b2eeab978f77',
    messagingSenderId: '318417662678',
    projectId: 'antriqu-apps',
    databaseURL:
        "https://antriqu-apps-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: 'antriqu-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH0G7qxCC5rCTVw71DW4KCqU_YStMt49Q',
    appId: '1:318417662678:ios:1f79483b6eefdd08978f77',
    messagingSenderId: '318417662678',
    projectId: 'antriqu-apps',
    databaseURL:
        "https://antriqu-apps-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: 'antriqu-apps.appspot.com',
    iosBundleId: 'com.example.apllicationBookNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH0G7qxCC5rCTVw71DW4KCqU_YStMt49Q',
    appId: '1:318417662678:ios:1f79483b6eefdd08978f77',
    messagingSenderId: '318417662678',
    projectId: 'antriqu-apps',
    databaseURL:
        "https://antriqu-apps-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: 'antriqu-apps.appspot.com',
    iosBundleId: 'com.example.apllicationBookNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXuFfVFHx90cB7tSq28evDz2Gqh8AZwbU',
    appId: '1:318417662678:web:35cd66fbe0367d65978f77',
    messagingSenderId: '318417662678',
    projectId: 'antriqu-apps',
    databaseURL:
        "https://antriqu-apps-default-rtdb.asia-southeast1.firebasedatabase.app",
    authDomain: 'antriqu-apps.firebaseapp.com',
    storageBucket: 'antriqu-apps.appspot.com',
    measurementId: 'G-P5ZC65DKM8',
  );
}
